### ISSUE TITLE
Suggestion: Add Path Legend

### ISSUE THREAD

**Issue by avatard** [Neop/mudmap2#10]
[v2.4.5](https://github.com/Neop/mudmap2/releases/tag/v2.4.5)
- [x] Under the Export as image dialog, include option to Export Path Legend.
  - [x] If selected, the exported image would also include a Path Legend, including its Directions and colors.
  - [ ] The Export Path Legend option would also include an option such as "Include only referenced Paths," in which case, only the Paths utilized in the selected view would be included in the Path Legend.

**Comment by Neop** [comment]
Implemented in https://github.com/Neop/mudmap2/commit/34e86e5a13fed21c8f8334b6c71b1b0f744ecbf0. I did not implemented a check whether a path color is used on the shown map / view, but it shouldn't be too much work to be implemented later on if it is really needed.
