### ISSUE TITLE
Suggestion: Add Group Legend

### ISSUE THREAD

**Issue by avatard** [Neop/mudmap2#11]
[v2.4.5](https://github.com/Neop/mudmap2/releases/tag/v2.4.5)
- [x] Under the Export as image dialog, include option to Export Group Legend.
  - [x] If selected, the exported image would also include a Group Legend, including its Names and colors.
  - [ ] The Export Group Legend option would also include an option such as "Include only referenced Groups," in which case, only the Groups utilized in the selected view would be included in the Group Legend.

**Comment by Neop** [comment]
I like these suggestions (#9, #10, #11). I considered adding a legend a while back but something kept me from implementing it. It's definitely an important feature, I'll try to find a way to implement it.

**Comment by Neop** [comment]
Implemented in https://github.com/Neop/mudmap2/commit/34e86e5a13fed21c8f8334b6c71b1b0f744ecbf0. There is an automatic check whether each group is actually used on the exported map (but no check whether it is in the shown view).
