### ISSUE TITLE
Suggestion: Implement File Extension For Worlds

### ISSUE THREAD

**Issue by avatard** [Neop/mudmap2#13]
I suggest **M2W** - I couldn't find an existing extension matching that.  It's minor, but allows for possible future capabilities such as simple importing/exporting Maps to/from Worlds.  In this scenario, maps might have the **M2M** extension.  Additionally, I'd set my IDE or NP++ up to handle/autoformat M2W as JSON (the existing format).

**Comment by Neop** [comment]
This is a good idea, making MUD Map files more distinguishable. Also, map export (which I imagine as world files stripped down to a single map, omitting all unused values/relations).
- [ ] world file extension
- [ ] map export (valid world file?)
- [ ] map import
