### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by denizzzka** [Neop/mudmap2#21]
It is need instruction for non Java users

**Comment by Neop** [comment]
I just added a description on how to build MUD Map to the README file.

You will need a Java 7 JDK and Maven. If you got the recent state of the repository then you can compile it by executing the following Maven command on a command line:
mvn package

If you're trying to compile an earlier state (earlier than today) then you could try these two commands:
mvn assembly:assembly
mvn assembly:single

You will find the JAR file mudmap2-2.x.x-jar-with-dependencies.jar in the target directory.
