### ISSUE TITLE
Comment Text Area Word Wrap/Height Issues

### ISSUE THREAD

**Issue by avatard** [Neop/mudmap2#26]
I noticed during comment creation.

A couple of issues: Open comment dialog, enter text.  It will move past the viewable portion of the pane.  Then resize the pane (horizontal and/or vertical).  The height of the input text area does not resize.

**Comment by avatard** [comment]
Done.  Checked into i26.

This might be considered an enhancement instead of a bug, or if it's a bug, a very minor one.

**Comment by Roxor007** [comment]
Hi, I am looking for some standard format for our mud maps in our guild. I am glad to see someone is working on such tool. (our 20+ years handwriten maps look a bit outdated :-) )
So, I was wondering if there is any way to display Comment field on tile (something like world settings for room id) . All i see is letters Co when i insert comment but not actual content of it.
I could really use that information , when connecting 2 maps. For example you want to connect ground floor of map (map 1) with 1st floor (map 2) and u want to say those floors are connected via hidden exit "enter statue". At the moment I have to name 1st room of Map 2 "Enter statue" to see "Ch: enter statue" on map1. But i want to use that name for something else :-(
Any chance to add that option or I am missing some existing option for this?
