### ISSUE TITLE
Mouse scroll zoom direction needs to be reversed

### ISSUE THREAD

**Issue by zaroth** [Neop/mudmap2#3]
The usual UI expectation/standard regarding zooming with mouse scroll is:

 - mouse scroll up zooms in
 - mouse scroll down zooms out

Examples: Google Maps, Firefox (ctrl+scroll), Chrome, OpenStreetMap, basically any map you find on the internet. Having to relearn that just for a mud mapper is really not the way to go IMHO.

**Comment by Neop** [comment]
Thanks for your feedback, I agree.
Here is the fixed release: https://github.com/Neop/mudmap2/releases/tag/v2.4.1
