### ISSUE TITLE
Suggestion: search comments

### ISSUE THREAD

**Issue by Ryner12** [Neop/mudmap2#30]
It would be useful to be able to search a map file for keywords -- including comments. I feel like this was possible in a previous version, but it no longer seems to be. I record monsters and objects within a room using comments, and it would be very handy to be able to find every location that contains "dragon," for example. Thank you.

**Comment by Neop** [comment]
I moved that function to the side bar. If you select the Places tab in the side bar you can search for places using the text box below. It will search for your key words in both the place names and their comments.
I'll add that information to the manual in the next release. Thanks for the hint!
