### ISSUE TITLE
Bug: Export as Image cuts off half of the eastern and southern most places

### ISSUE THREAD

**Issue by avatard** [Neop/mudmap2#32]
Settings: Current map, straight paths, transparent, path colors, place groups, position left.
I didn't try other settings to see if I get different results.

The map itself has a place with a path connecting to a place on a different map.  I doubt that's related, but including the info just in case.

The world file was originally created under an older version of MUD Map.

**Comment by Neop** [comment]
Fixed: The bug was caused by a mistake in converting tile coordinates to image coordinates.
