### ISSUE TITLE
Room background color

### ISSUE THREAD

**Issue by jinkai** [Neop/mudmap2#35]
I have an idea for an enhancement:
Allow setting the background color for a room.

My use case:
There are certain aspects of the rooms in an area that I want to see at a glance - is there a known mob in the room? Or a known item/chest? Dangerous? Safe? Etc.

I can edit the name of a room to cover 1 aspect, but then I can't tell any of the others just looking at the map - I need to click on a room and look at any comments in there. I'd think setting the background color would let me have a color scheme to cover these aspects.

**Comment by Neop** [comment]
I suggest to use the 'risk level' setting to describe how dangerous or safe a place is. That will add a colored ring to the tile on the map. Setting a place group will add another ring (you could of course add risk levels for other meanings in the Worlds menu).

I think I could make the background color changable, but I'm not sure if it's that helpful if you want to show two or more information. Right now I got 3 ideas:
- I could try to make the background colors changable as you suggest - It will be up to you to manage a color scheme
- I could add a second text line to the tiles (think of a short comment line) - I used something similar in past versions of MUD Map, where one or two letters showed that a place has food or so.
- I could change the risk level system to a more general purpose. Say you want to mark a place with a chest you'll just add a color for 'here is a chest' and select that in the place settings

Which one do you think is the most useful?

**Comment by jinkai** [comment]
Hello! I looked into the risk level settings, and that is probably good enough, especially because I can add custom risk levels. Since we have that, I don't think custom background colors is that useful. I do think that the risk level could just be a general purpose "Indicators" system or something.

An extra line of short text would also be useful, I think. Combine that with a border color and people should be able to indicate whatever they need to. It would certainly cover my needs!

Thank you!
