### ISSUE TITLE
Suggestion: Permit self-linking paths

### ISSUE THREAD

**Issue by drislands** [Neop/mudmap2#36]
I'm playing through the original Zork right now and making great use of mudmap2, but there are a few locations (most notably in the Maze) where leaving by a certain exit brings you back to the room you started in. For ease of mapping such madness, it would be useful to be able to indicate where such self-loops are without having to create a separate Loop room (my current workaround).

**Comment by Neop** [comment]
I intend to use one-way paths for this, which you can create by setting the destination place's exit direction to "-" (without the quotation marks).

That said I found a bug that prohibits creating more than one one-way path to a place. I will try to fix that asap and let you know when it works.

**Comment by Neop** [comment]
I fixed the bug I mentioned. Here is the new version: https://github.com/Neop/mudmap2/releases/tag/v2.5.4

I hope this helps, tell me if you got some other suggestion or if there's an issue.
