### ISSUE TITLE
List dialog for maps

### ISSUE THREAD

**Issue by Neop** [Neop/mudmap2#45]
The side bar can be used to create and rename maps but not for removing or ordering. Add a list dialog for adding, removing, changing and ordering maps.

**Comment by jinkai** [comment]
Howdy! I love this program. And I'd love the ability to delete Maps! I use this to map out some areas that are randomly generated, and I just want to delete the map when I'm done, but I haven't found a way to do so. So having this dialog would be perfect. :)

**Comment by Neop** [comment]
Thanks for the hint, I'll look into it this weekend!

**Comment by Neop** [comment]
Done! I added a context menu to the maps side bar that you can use to change and delete maps. You can get the new release here: https://github.com/Neop/mudmap2/releases/tag/v2.5.8

**Comment by jinkai** [comment]
Just pulled down the release and checked it out, works great. Thank you!
