### ISSUE TITLE
Connect path can not connect a place with itself

### ISSUE THREAD

**Issue by Neop** [Neop/mudmap2#48]

**Comment by marplar** [comment]
I can connect a place to itself with Paths > Connect > Select. However then when I save and later try to reopen it reports the error 'Could not open world: Can not connect path to the same exit of one place'. To get the file to open I have to edit the file for example [{"p":56,"e":"s"},{"p":56,"e":"s"}] must be changed to [{"p":56,"e":"s"},{"p":56,"e":"-"}]. I am not sure if this is the same bug or a new one. Using version 2.5.6

**Comment by Neop** [comment]
Thanks for your bug report!
I found and fixed a few issues about places that connect to themselves, including the first exit being written to the file twice.
You can get the new version here: https://github.com/Neop/mudmap2/releases/tag/v2.5.7

I forgot what my original issue was about, so I'm just closing this.

**Comment by marplar** [comment]
Thanks a lot for the very quick fix! I confirm its working well in the new version :)
