### ISSUE TITLE
Feature Request: Allow exits with no connection

### ISSUE THREAD

**Issue by jinkai** [Neop/mudmap2#52]
Hello! I'd love to be able to add exits that don't connect to another place yet.
Use Case:
As I'm mapping an area and I add a Place for a room that has n/s/e/w exits, and I decide to continue mapping to the north (coming from the south), I'd like to add the exits for e/w even though they don't connect to anything yet so I know to come back and continue mapping.

My current workaround is to use a colored info ring so I know to come back to that Place, but having the exit visible would be ideal.

Thanks!

**Comment by Neop** [comment]
Thanks for your suggestion!
I had intended to use placeholder places for this purpose but I see that this approach might not be ideal.
With new version you can use a dialog in the context menu to create exits to unknown places. These exits will be marked in a different color.
You can download it here: https://github.com/Neop/mudmap2/releases/tag/v2.5.9

**Comment by jinkai** [comment]
The marker looks good! But I typically just use hotkeys to do everything - any chance of having it work with the normal ctrl + arrow key or ctrl + numpad for adding an unknown exit if there isn't a place to connect to? Or ctrl + shift/alt + numpad?

This will still help with mapping the randomly generated areas. Thanks for the update!

**Comment by Neop** [comment]
That's a good idea, I forgot about the shortcuts... I'll try to add it tomorrow.

**Comment by Neop** [comment]
I added it to the ctrl+numpad commands: if no connection to an adjacent place can be made an unconnected exit will be created.
Here is the new release: https://github.com/Neop/mudmap2/releases/tag/v2.6.0

**Comment by jinkai** [comment]
Just downloaded it and tried it out. Initially, it works great! But I found another scenario I'm wondering how to handle: if you have an unconnected exit in a direction, and then add a place that it would connect to later, you can't use hotkeys to connect it. If you try to connect from the new place back to the original, you get an unconnected exit on the new place. And the hotkey to connect does nothing on the old place, I'm guessing since there's already some form of exit there.

I opened the exits menu, and I saw that "alt + numpad" should remove an exit in the appropriate direction. Those hotkeys don't seem to work, for either connected or unconnected exits. If that worked for both types of exits, then I don't see a need to try and solve the "connect to an unconnected exit" scenario above - I can easily hotkey to remove, and then hotkey add.

Thanks for all the work, I'm still loving this program for mapping areas.

**Comment by Neop** [comment]
I'm glad you like mudmap and that you send me these suggestions. I tend to miss such issues since I don't use it myself.
I fixed the "alt + numpad" issue, you can remove exits now. I decided not to do some kind of automatic replacement of unconnected exits though to avoid accidentally replacing those. I guess it's a 50/50 decision on that feature...
You'll find the fixed version here: https://github.com/Neop/mudmap2/releases/tag/v2.6.1
