### ISSUE TITLE
Exit by selection is almost off the screen

### ISSUE THREAD

**Issue by jackc59** [Neop/mudmap2#6]
When I choose to add an exit using Paths and Exits, Connect, then Select, the selection screen is so far to the top left that I can't reach the top bar to move it around, and I can't see the cancel button.  Lengthening it will let me see the cancel button, but starting it again goes back to the way it was, and I still can't get to the top.

**Comment by Neop** [comment]
Thanks alot for your feedback!
I'm aware of that bug but I had no time to fix it yet. I will try to look into it in a week.

Workaround: Resizing the window works for me, the window then pops put of the border (or moves down enough to grab it's title bar, tested with a Windows 8 system).

**Comment by jackc59** [comment]
Thanks! Is there a way to be notified when updates happen?

**Comment by Neop** [comment]
I'll write a comment and close this issue when I solved it. You can also watch this repository to be notified of any changes (look out for new releases)

**Comment by Neop** [comment]
The issue should be fixed in https://github.com/Neop/mudmap2/releases/tag/v2.4.5
